In [ ]:
#sshfs tbellagio@calc.carnegiescience.edu:/carnegie/nobackup/scratch/tbellagio/pang /Users/tatiana/Documents_new/pangenomes
# diskutil unmount force /Users/tatiana/Documents_new/pangenomes


sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 \
tbellagio@calc.carnegiescience.edu:/carnegie/nobackup/scratch/tbellagio/pang \
/Users/tatiana/Documents_new/pangenomes

In [1]:
import pandas as pd

In [2]:
## the first step will be to check how mnay of the accessions we have for grenent are present in the already avilable/soon to be 1001 g projects and how many are not

In [2]:
pang_69 = pd.read_csv('23_ara_pang/accessions.csv')

In [3]:
pang_23 = pd.read_csv('69_ara_pang/accessions.csv', skiprows=2)

In [4]:
lr_1001= pd.read_csv('long_read_seq_ara/Athaliana_assembly_IDs_OVERVIEW.csv')

In [5]:
grenenet = pd.read_csv('long_read_seq_ara/grene_ecotypes.csv')[['ID', 'name', 'country']]
grenenet = grenenet.dropna()
grenenet['acc_ID'] = grenenet['ID'].astype(int)

In [ ]:
accessions = pd.read_csv('1001g_accesions_list.csv', )

In [8]:
accessions

,88,Monsanto,CYR,FRA,CYR.1,47.4,0.683333,Valerie Le Corre,Unnamed: 8,CS76790,western_europe,Unnamed: 11,blu_circle
0,108,Monsanto,LDV-18,FRA,LDV,48.516700,-4.066670,Valerie Le Corre,NaN,CS77013,western_europe,NaN,blu_circle
1,139,Monsanto,LDV-46,FRA,LDV,48.516700,-4.066670,Valerie Le Corre,NaN,CS77014,western_europe,NaN,blu_circle
2,159,Monsanto,MAR2-3,FRA,Mar2,47.350000,3.933330,Valerie Le Corre,NaN,CS77070,western_europe,NaN,blu_circle
3,265,Monsanto,PYL-6,FRA,PYL,44.650000,-1.166670,Valerie Le Corre,NaN,CS77198,admixed,NaN,forbidden
4,350,Monsanto,TOU-A1-88,FRA,TOU-A1,46.666700,4.116670,Fabrice Roux,NaN,CS77382,western_europe,NaN,blu_circle
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129,18694,GMI,Pien,RUS,Pienisartosari,60.400000,32.090000,Magnus Nordborg,2012-01-06 0:00:00,CS78926,asia,NaN,purple_circle
1130,18696,GMI,Samm,RUS,Sammatsari,61.570000,30.630000,Magnus Nordborg,2012-01-06 0:00:00,CS78929,asia,NaN,purple_circle
1131,19949,GMI,OOE2-1,AUT,Oberoesterreich,48.326833,14.718167,Wolfram Weckwert,NaN,CS79036,central_europe,NaN,ylw_circle
1132,19950,GMI,OOE2-2,AUT,Oberoesterreich,48.326833,14.718167,Wolfram Weckwert,NaN,CS79037,central_europe,NaN,ylw_circle
1133,19951,GMI,OOE23,AUT,Oberoesterreich,48.326833,14.718167,Wolfram Weckwert,NaN,CS79038,central_europe,NaN,ylw_circle

In [17]:
grenenet.head()

      ID    name country
0  159.0  MAR2-3     FRA
1  265.0   PYL-6     FRA
2  763.0   Kar-1     KGZ
3  765.0   Sus-1     KGZ
4  766.0   Dja-1     KGZ

In [13]:
lr_1001.head()

,Assembly_ID,Accession_Name,Accession_ID,Accession_alias,Original_Assembly_ID,Version,QC_pipeline,Final_assembly,TMP_comments,CSnumber,...,Assembler,Individual_or_pool,Latest_released_Year,Published,Publication_First_author,Publication_year,Publication_Journal,Publication_DOI,Publication_URL,Best_unique_assembly
0,100000,Col-0,6909,TAIR10,NaN,1.0,NaN,False,NaN,NaN,...,NaN,Pool,NaN,yes,NaN,NaN,NaN,NaN,NaN,0.0
1,100001,Col-0,6909,TAIR12 version 1,100001.0,1.0,NaN,False,NaN,NaN,...,NaN,Pool,2023.0,no,TAIR,NaN,unpublished,NaN,NaN,0.0
2,100002,Col-0,6909,TAIR12 version 2,100001.0,2.0,NaN,True,NaN,NaN,...,NaN,Pool,2023.0,no,TAIR,NaN,unpublished,NaN,NaN,1.0
3,100003,Ler-0,7213,NaN,NaN,NaN,NaN,False,Not avaiable,NaN,...,NaN,NaN,NaN,yes,Berlin,2015.0,NatBiotechnol,10.1038/nbt.3238,https://www.nature.com/articles/nbt.3238,NaN
4,100004,F1 (Col-0/Cvi-0),6909/6911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,yes,Chin,2016.0,NatMethods,10.1038/nmeth.4035,https://www.nature.com/articles/nmeth.4035,NaN

In [11]:
pang_23.head()

,Accession,Acc_ID,Country,Latitude,Longitude,Long-read technology,Long-read size (Gb),"Long-read (N50, bp)",Long-read depths,Short-read depths
0,Db-1,132AV,Germany,50.28,8.36,Pacbio HiFi,6.56,15504,52,30
1,Est-0,71AV,Estonia,59.45,24.76,Pacbio HiFi,4.37,14876,34,31
2,Kas-1,108AV,India,34.2,76.83,Pacbio HiFi,4.17,15807,33,28
3,Lu-1,54AV,Sweden,55.72,13.19,Pacbio HiFi,9.22,17516,73,31
4,Mh-0,175AV,Poland,52.24,21.01,Pacbio HiFi,8.53,16640,67,32

In [10]:
pang_69.head()

,Name,CS_Number,Country,Latitude,Longitude,Altitude,Group
0,Yilong-0,CS79063,China,31.56402,106.7062,506,Non-Relict
1,Bor-1,CS22590,Czech Republic,49.40130,16.2326,697,Non-Relict
2,Cdm-0,CS76410,Spain,39.73000,-5.7400,157,Non-Relict
3,Got-22,CS22609,Germany,51.53380,9.9355,310,Non-Relict
4,Kondara,CS22651,Tajikistan,38.48000,68.4900,641,Non-Relict