In [2]:
import pandas as pd

/tmp/ipykernel_215463/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [5]:
pd.read_csv('pangraph_output/stats/sample-stats.tsv', header=None, sep='\t')

           0          1         2
0       Chr1  Altai-5#0  28897887
1       Chr1    Anz-0#0  29381478
2       Chr1    Can-0#0  29326251
3       Chr1    Col-0#0  32215923
4       Chr1     Ct-1#0  29447756
..       ...        ...       ...
91      Chr5    Stw-0#0  26789651
92      Chr5    Sus-1#0  27008355
93      Chr5  Toufl-1#0  26846743
94      Chr5    Zal-1#0  26430554
95  chrOther    Col-0#0     14346

[96 rows x 3 columns]

In [6]:
pd.read_csv('pangraph_output/stats/clip-stats.bed', header=None, sep='\t')

                                      0     1     2         3
0                  _MINIGRAPH_#0#s10687     0   233      Chr1
1      _MINIGRAPH_#0#s117378[2139-2157]  2157  2175      Chr1
2        _MINIGRAPH_#0#s8687[2973-2980]  2980  2987      Chr1
3                  _MINIGRAPH_#0#s16985     0  2536      Chr1
4                  _MINIGRAPH_#0#s17396     0   197      Chr1
...                                 ...   ...   ...       ...
60655              _MINIGRAPH_#0#s76850     0  3488  chrOther
60656              _MINIGRAPH_#0#s76852     0  3745  chrOther
60657              _MINIGRAPH_#0#s76851     0  1628  chrOther
60658              _MINIGRAPH_#0#s76847     0  1085  chrOther
60659              _MINIGRAPH_#0#s76849     0  2942  chrOther

[60660 rows x 4 columns]

In [7]:
pd.read_csv('pangraph_output/stats/graph-stats.tsv', header=None, sep='\t')

           0       1         2
0       Chr1   nodes   3405474
1       Chr1   edges   4660204
2       Chr1  length  48428282
3       Chr2   nodes   2325568
4       Chr2   edges   3178428
5       Chr2  length  33373818
6       Chr3   nodes   2745054
7       Chr3   edges   3751454
8       Chr3  length  40446415
9       Chr4   nodes   2256401
10      Chr4   edges   3082784
11      Chr4  length  31305643
12      Chr5   nodes   3118244
13      Chr5   edges   4264562
14      Chr5  length  42452678
15  chrOther   nodes        17
16  chrOther   edges        11
17  chrOther  length     14346

In [8]:
pd.read_csv('pangraph_output/stats/path-stats.tsv', header=None, sep='\t')

            0                                        1         2
0        Chr1               Kar-1#0#Chr1#0[2-14480928]  14480926
1        Chr1        Dog-4#0#Chr1#0[14585508-14638679]     53171
2        Chr1             Toufl-1#0#Chr1#0[1-14363392]  14363391
3        Chr1  Rubezhnoe-1#0#Chr1#0[18432455-27323996]   8891541
4        Chr1        Anz-0#0#Chr1#0[17376241-17394749]     18508
..        ...                                      ...       ...
443  chrOther                       Col-0#0#contig_354      1628
444  chrOther                       Col-0#0#contig_311      3488
445  chrOther                       Col-0#0#contig_189      1458
446  chrOther                       Col-0#0#contig_165      1085
447  chrOther                       Col-0#0#contig_379      3745

[448 rows x 3 columns]

In [5]:
nodes_coverage = pd.read_csv('run_vg_giraffe/MLFH041020180321.node_coverage.tsv', sep='\t', nrows = 1000)

In [6]:
nodes_coverage

     seq.pos  node.id  node.offset  coverage
0          0  3264413            0         0
1          1  3264413            1         0
2          2  1514651            0         5
3          3  8461484            0         0
4          4  8461484            1         0
..       ...      ...          ...       ...
995      995  2071891           15         7
996      996  2071891           16         7
997      997  2071891           17         8
998      998  2071891           18         8
999      999  2071891           19         8

[1000 rows x 4 columns]