In [21]:
import pandas as pd

In [22]:
import pandas as pd
from pathlib import Path
import numpy as np

BASE = Path("/home/tbellagio/scratch/pang/test_freqk/run_set_02_rep1_S1/")

In [ ]:
# --- index (chrom/pos) ---
idx_path = BASE / f"set_02_rep1.k31.freqk.ref_index"
idx = pd.read_csv(idx_path, header=None)[[1,2]]

idx.columns = ["chrom", "pos"]
idx["chrom"] = idx["chrom"].astype(str)
idx["pos"] = idx["pos"].astype(int) + 2   # keep your +2 correction
af_path = BASE / "S1.allele_frequencies.k31.dedup.tsv"

rows = []
max_cols = 0

with open(af_path, "r") as f:
    for line in f:
        parts = line.rstrip("\n").split("|")
        rows.append(parts)
        if len(parts) > max_cols:
            max_cols = len(parts)

# pad
rows = [r + [np.nan] * (max_cols - len(r)) for r in rows]

af = pd.DataFrame(rows, columns=[f"c{i}" for i in range(max_cols)])

af.columns = ['ref', 'alt1', 'alt2']

df = pd.concat([idx.reset_index(drop=True),
                     af],
                    axis=1)

In [57]:
hapfm = pd.read_csv('../grenenet_reads/average_seedmix_p0.txt',sep = '\t', header=None)

In [58]:
hapfm

         0         1         2
0        1       291  0.037575
1        1       346  0.264121
2        1       349  0.010239
3        1       352  0.020212
4        1       353  0.067621
...     ..       ...       ...
3235475  5  26975208  0.012561
3235476  5  26975215  0.016091
3235477  5  26975267  0.004589
3235478  5  26975272  0.410081
3235479  5  26975288  0.197647

[3235480 rows x 3 columns]

In [14]:
import allel
vcf = allel.read_vcf('run_set_02_rep1_S1/set_02_rep1.deconstruct.top.renamed.vcf.gz')

chrom = vcf['variants/CHROM']
pos = vcf['variants/POS']

variants_vcf = pd.DataFrame({
    "chrom": chrom,
    "pos": pos
})

variants_vcf

       chrom       pos
0       Chr1         2
1       Chr1       892
2       Chr1      1079
3       Chr1      6324
4       Chr1      8677
...      ...       ...
786713  Chr5  26975099
786714  Chr5  26975288
786715  Chr5  26975377
786716  Chr5  26975423
786717  Chr5  26975498

[786718 rows x 2 columns]

In [17]:
import allel

path = '/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/set_02_rep1/output/set_02_rep1.deconstruct.top.vcf.gz'
vcf = allel.read_vcf(path)

chrom = vcf['variants/CHROM']
pos = vcf['variants/POS']

variants_vcf = pd.DataFrame({
    "chrom": chrom,
    "pos": pos
})

variants_vcf

                chrom       pos
0       TAIR10#0#Chr1         2
1       TAIR10#0#Chr1       892
2       TAIR10#0#Chr1      1079
3       TAIR10#0#Chr1      6324
4       TAIR10#0#Chr1      8677
...               ...       ...
786713  TAIR10#0#Chr5  26975099
786714  TAIR10#0#Chr5  26975288
786715  TAIR10#0#Chr5  26975377
786716  TAIR10#0#Chr5  26975423
786717  TAIR10#0#Chr5  26975498

[786718 rows x 2 columns]

In [18]:
base_path = '/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/'

snarls = pd.read_csv(base_path + 'set_02_rep1/output/qc/qc_sizes_biallelic.set_02_rep1.deconstruct.top.tsv', sep = '\t')

In [19]:
snarls['chrom'] = snarls['chrom'].str.split('#').str[-1]

In [ ]:
import allel

path = '/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/set_10_rep3/output/set_10_rep3.vcf.gz'
vcf = allel.read_vcf(path)

chrom = vcf['variants/CHROM']
pos = vcf['variants/POS']

variants_vcf = pd.DataFrame({
    "chrom": chrom,
    "pos": pos
})

variants_vcf

In [77]:
base_path = '/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/'

snarls = pd.read_csv(base_path + 'set_10_rep3/output/qc/qc_sizes_biallelic.set_10_rep3.tsv', sep = '\t')

In [78]:
snarls_svs = snarls[snarls['class'] != 'SNP']
snarls_svs = snarls_svs[snarls_svs['class'] != 'MNP']

In [79]:
snarls_svs['class'].value_counts()

class
DEL    266901
INS    265895
Name: count, dtype: int64

In [81]:
snarls.head(50)

   chrom   pos          id class  size_signed  size_bp  is_conflict
0   Chr1     1     >6>1361   INS         3591     3591            0
1   Chr1     1     >6>1361   INS         5001     5001            0
2   Chr1     1     >6>1361   INS         5260     5260            0
3   Chr1     1     >6>1361   INS         1652     1652            0
4   Chr1     1     >6>1361   INS         1408     1408            0
5   Chr1     1     >6>1361   INS         3645     3645            0
6   Chr1     1     >6>1361   INS         3477     3477            0
7   Chr1     1     >6>1361   INS         4176     4176            0
8   Chr1  1722  >1361>1365   DEL           -6        6            0
9   Chr1  1722  >1361>1365   MNP            0        0            0
10  Chr1  1733  >1365>1388   INS         1376     1376            0
11  Chr1  1733  >1365>1388   INS         1372     1372            0
12  Chr1  1733  >1365>1388   INS         1369     1369            0
13  Chr1  1738  >1388>1391   SNP            0        0            0
14  Chr1  1739  >1391>1393   INS            7        7            0
15  Chr1  1741  >1393>1396   SNP            0        0            0
16  Chr1  1743  >1396>1399   SNP            0        0            0
17  Chr1  1745  >1399>1402   SNP            0        0            0
18  Chr1  1751  >1402>1405   MNP            0        0            0
19  Chr1  1756  >1405>1408   MNP            0        0            0
20  Chr1  1764  >1408>1410   DEL         -163      163            0
21  Chr1  2231  >1410>1413   SNP            0        0            0
22  Chr1  2290  >1413>1416   SNP            0        0            0
23  Chr1  2309  >1416>1419   MNP            0        0            0
24  Chr1  2330  >1419>1421   INS            2        2            0
25  Chr1  2718  >1421>1423   DEL           -4        4            0
26  Chr1  2748  >1423>1426   SNP            0        0            0
27  Chr1  2778  >1426>1428   INS            7        7            0
28  Chr1  2826  >1428>1431   SNP            0        0            0
29  Chr1  2881  >1431>1434   SNP            0        0            0
30  Chr1  2966  >1434>1437   SNP            0        0            0
31  Chr1  3032  >1437>1440   SNP            0        0            0
32  Chr1  3102  >1440>1443   SNP            0        0            0
33  Chr1  3415  >1443>1446   SNP            0        0            0
34  Chr1  3566  >1446>1448   INS            1        1            0
35  Chr1  4287  >1448>1451   SNP            0        0            0
36  Chr1  4290  >1451>1458   DEL          -14       14            0
37  Chr1  4290  >1451>1458   DEL          -20       20            0
38  Chr1  4290  >1451>1458   DEL           -4        4            0
39  Chr1  4290  >1451>1458   DEL           -2        2            0
40  Chr1  4290  >1451>1458   DEL          -18       18            0
41  Chr1  4290  >1451>1458   DEL          -12       12            0
42  Chr1  4313  >1458>1461   SNP            0        0            0
43  Chr1  4315  >1461>1464   MNP            0        0            0
44  Chr1  4412  >1464>1467   SNP            0        0            0
45  Chr1  4426  >1467>1469   INS            8        8            0
46  Chr1  4648  >1469>1472   SNP            0        0            0
47  Chr1  4880  >1472>1475   SNP            0        0            0
48  Chr1  5427  >1475>1478   SNP            0        0            0
49  Chr1  5679  >1478>1481   INS            1        1            0

In [28]:
df.shape

(579593, 5)

In [54]:
snarls_freq = snarls.merge(df, on =['chrom', 'pos'])

In [55]:
snarls_freq

,chrom,pos,id,class,size_signed,size_bp,is_conflict,ref,alt1,alt2
0,Chr1,892,>8>11,SNP,0,0,0,0,1,NaN
1,Chr1,1079,>11>13,DEL,-3,3,0,0.72,0.28,NaN
2,Chr1,6324,>18>20,INS,1,1,0,0,1,NaN
3,Chr1,8677,>22>24,INS,2,2,0,NaN,NaN,NaN
4,Chr1,10904,>26>29,SNP,0,0,0,0.9297246,0.0702754,NaN
...,...,...,...,...,...,...,...,...,...,...
579599,Chr5,26975078,>2349296>2349299,SNP,0,0,0,0.12864079,0.8713592,NaN
579600,Chr5,26975099,>2349299>2349302,SNP,0,0,0,0.66831684,0.33168316,NaN
579601,Chr5,26975288,>2349302>2349305,SNP,0,0,0,0.56697816,0.43302178,NaN
579602,Chr5,26975377,>2349305>2349308,SNP,0,0,0,0.71273714,0.2872629,NaN
579603,Chr5,26975423,>2349308>2349310,DEL,-7,7,0,0.5253164,0.47468355,NaN

In [ ]:
bcftools query -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\n' set_10_rep3.vcf.gz \
| awk -F'\t' '
{
  ref=$4; split($5,alts,",");
  printf("%s\t%s\t%s\tref_len=%d\tNalt=%d", $1,$2,$3,length(ref),length(alts));
  for(i=1;i<=length(alts);i++){
    printf("\talt%d_len=%d\talt%d_dlen=%+d", i,length(alts[i]),i,(length(alts[i])-length(ref)));
  }
  printf("\n");
}'

In [ ]:
bcftools +fill-tags -Ou set_10_rep3.vcf.gz -- -t AC,AN \
| bcftools query -f '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%AC\t%AN\n' \
| head

In [59]:
hapfm

         0         1         2
0        1       291  0.037575
1        1       346  0.264121
2        1       349  0.010239
3        1       352  0.020212
4        1       353  0.067621
...     ..       ...       ...
3235475  5  26975208  0.012561
3235476  5  26975215  0.016091
3235477  5  26975267  0.004589
3235478  5  26975272  0.410081
3235479  5  26975288  0.197647

[3235480 rows x 3 columns]

In [36]:
snarls

,chrom,pos,id,class,size_signed,size_bp,is_conflict
0,Chr1,2,>1>8,INS,5919,5919,0
1,Chr1,892,>8>11,SNP,0,0,0
2,Chr1,1079,>11>13,DEL,-3,3,0
3,Chr1,6324,>18>20,INS,1,1,0
4,Chr1,8677,>22>24,INS,2,2,0
...,...,...,...,...,...,...,...
786740,Chr5,26975099,>2349299>2349302,SNP,0,0,0
786741,Chr5,26975288,>2349302>2349305,SNP,0,0,0
786742,Chr5,26975377,>2349305>2349308,SNP,0,0,0
786743,Chr5,26975423,>2349308>2349310,DEL,-7,7,0
786744,Chr5,26975498,>2349310>2349313,SNP,0,0,0

In [ ]:
382473

In [ ]:
386408

In [53]:
pd.read_csv('/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/set_02_rep1/seqfile.txt')

  TAIR10\t/home/tbellagio/scratch/pang/pang_experiment/genomes/TAIR10.fasta
0  No-0\t/home/tbellagio/scratch/pang/pang_experi...

In [51]:
path_graph = '/carnegie/nobackup/scratch/tbellagio/pang/pang_experiment/pangenomes/'
vcf = allel.read_vcf(path_graph + 'set_02_rep1/output/set_02_rep1.deconstruct.all_snarls.biallelic.norm.vcf.gz')

chrom = vcf['variants/CHROM']
pos = vcf['variants/POS']


alts = vcf["variants/ALT"]          # shape ~ (n_variants, max_alts)
alts_len_flat = [
    len(a) for row in alts for a in row
    if a not in (None, "", ".") and not (isinstance(a, str) and a.startswith("<"))
]

variants_vcf = pd.DataFrame({
    "chrom": chrom,
    "pos": pos,
    "len" : alts_len_flat
})

variants_vcf['chrom'] = variants_vcf['chrom'].str.split('#').str[-1]

In [52]:
variants_vcf

       chrom       pos   len
0       Chr1         2  5920
1       Chr1       892     1
2       Chr1      1079     1
3       Chr1      6324     2
4       Chr1      8677     3
...      ...       ...   ...
802488  Chr5  26975099     1
802489  Chr5  26975288     1
802490  Chr5  26975377     1
802491  Chr5  26975423     1
802492  Chr5  26975498     1

[802493 rows x 3 columns]

In [32]:
path_sv_panel = '/home/tbellagio/scratch/pang/sv_panel/syri/results/No-0/'

In [34]:
vcf_syri = allel.read_vcf(path_sv_panel + 'No-0.tair10.syri.vcf')

In [37]:
chrom = vcf_syri['variants/CHROM']
pos = vcf_syri['variants/POS']
varid = vcf_syri['variants/ID']


variants_syri = pd.DataFrame({
    "chrom": chrom,
    "pos": pos,
    'varid' : varid
})

In [39]:
variants_syri["varid_letters"] = variants_syri["varid"].str.replace(r"\d+", "", regex=True)

In [42]:
variants_syri

       chrom       pos      varid varid_letters
0       Chr1         1     SYNAL1         SYNAL
1       Chr1         1       SYN1           SYN
2       Chr1       892    SNP4290           SNP
3       Chr1      1075    DEL4291           DEL
4       Chr1      6324    INS4292           INS
...      ...       ...        ...           ...
526737  Chr5  26975078  SNP520323           SNP
526738  Chr5  26975099  SNP520324           SNP
526739  Chr5  26975288  SNP520325           SNP
526740  Chr5  26975377  SNP520326           SNP
526741  Chr5  26975498   NOTAL226         NOTAL

[526742 rows x 4 columns]

In [41]:
variants_syri['varid_letters'].value_counts()

varid_letters
SNP        428692
INS         44324
DEL         42974
SYNAL        4350
HDR          4207
DUPAL         449
INVDPAL       382
DUP           348
INVDP         334
NOTAL         226
SYN           114
INVTRAL        66
TRANSAL        60
INVAL          49
TRANS          49
INVTR          42
CPG            27
INV            23
CPL            17
TDM             9
Name: count, dtype: int64

In [82]:
import pysam
import re
from collections import Counter

vcf = pysam.VariantFile("/home/tbellagio/scratch/pang/test_postproc/set_10_rep3.vcf.gz")

bad = 0
total_multi = 0
examples = []

for rec in vcf:
    k = len(rec.alts or [])
    if k < 2:
        continue
    total_multi += 1

    used = [False] * (k + 1)  # used[j] for j=1..k

    for s in rec.samples.values():
        gt = s.get("GT", None)
        if gt is None:
            continue
        # gt is a tuple like (0,2) or (1,) or (None,None)
        for a in gt:
            if a is None:
                continue
            if 1 <= a <= k:
                used[a] = True

    if not all(used[1:]):
        bad += 1
        if len(examples) < 10:
            missing = [j for j in range(1, k+1) if not used[j]]
            examples.append((rec.chrom, rec.pos, rec.id, k, missing))

print("multiallelic sites:", total_multi)
print("sites with any unused ALT:", bad)
print("example bad sites:", examples)

multiallelic sites: 179652
sites with any unused ALT: 0
example bad sites: []

In [ ]:
bcftools view -a set_10_rep3.vcf.gz | wc -l bcftools +counts

In [84]:
pd.read_csv('../grenenet_reads/grenenet_samples_inventory_savio.csv')

,release,sample,fastq1,fastq2,sample_path,date,year
0,2021-01-29-ath-release-01,MLFH10_1_20180130,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180130.0,2018.0
1,2021-01-29-ath-release-01,MLFH10_1_20180215,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180215.0,2018.0
2,2021-01-29-ath-release-01,MLFH10_1_20180301,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180301.0,2018.0
3,2021-01-29-ath-release-01,MLFH10_1_20190206,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20190206.0,2019.0
4,2021-01-29-ath-release-01,MLFH10_2_20180130,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180130.0,2018.0
...,...,...,...,...,...,...,...
1793,2021-05-17-ath-release-08,MLFH600920180216,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180216.0,2018.0
1794,2021-05-17-ath-release-08,MLFH600920180420,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180420.0,2018.0
1795,2021-05-17-ath-release-08,MLFH601020180216,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180216.0,2018.0
1796,2021-05-17-ath-release-08,MLFH601020180420,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,20180420.0,2018.0
1797,2021-05-17-ath-release-08,Undetermined,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,/global/scratch/projects/fc_moilab/RAW/SRA/gre...,NaN,NaN

In [89]:
site4 = pd.read_csv('../grenenet_reads/site4_fastqs_to_transfer.txt',header=None)

In [93]:
site4[0].str.split('/').str[-1].to_csv('../grenenet_reads/site4_fastqs_names.txt')

In [ ]:
pd.

In [ ]:
ATCATACACATGACATCAAGTCATATTCGACTCCAAAACACTAACCAACC
ATCATACACATGACATCAAGTCATATTCGACTCCAAAACACTAACCAACC